sylius_fixtures:
    suites:
        default:
            listeners:
                orm_purger: ~
                logger: ~

            fixtures:
                user:
                    options:
                        random: 5
                        custom:
                            -
                                email: "user@example.com"
                                password: "password"
                            -
                                email: "not.verified@example.com"
                                password: "password"
                                verified: false
                                token: "thisisagreattoken"
                travel:
                    options:
                        random: 20
                        custom:
                            -
                                name: "Rome"