sylius_fixtures:
    suites:
        default:
            listeners:
                orm_purger: ~
                logger: ~

            fixtures:
                user:
                    options:
                        random: 5
                        custom:
                            -
                                email: "user@example.com"
                                password: "password"
                            -
                                email: "not.verified@example.com"
                                password: "password"
                                verified: false
                                token: "ThisIsAGreatToken"
                travel:
                    options:
                        random: 20
                        custom:
                            -
                                name: "Dubrovnik"
                                summary: "Old trip to Croatia"
                                date_start: "-2 weeks"
                                date_end: "-1 weeks"
                                user: "user@example.com"
                            -
                                name: "Rome"
                                summary: "Current trip to Italy!"
                                date_start: "-1 week"
                                date_end: "+1 week"
                                user: "user@example.com"
                            -
                                name: "Porto"
                                summary: "Next trip to Portugal"
                                date_start: "+1 week"
                                date_end: "+2 week"
                                user: "user@example.com"

                accomodation_step:
                    options:
                        random: 20
