app_authentication_register:
  path: /auth/register
  defaults:
    _controller: AppBundle:Authentication:register

app_authentication_register_confirm:
  path: /auth/register/confirm
  defaults:
    _controller: AppBundle:Authentication:registerConfirm