app_authentication_register:
  path: /auth/register
  defaults:
    _controller: AppBundle:Authentication:register
  methods: [POST]

app_authentication_register_confirm:
  path: /auth/register/confirm
  defaults:
    _controller: AppBundle:Authentication:registerConfirm
  methods: [POST]

app_authentication_login:
  path: /auth/login
  defaults:
    _controller: AppBundle:Authentication:login
  methods: [POST]

app_authentication_refresh:
  path: /auth/refresh
  defaults:
    _controller: gesdinet.jwtrefreshtoken:refresh
  methods: [POST]