app_step_attachment_list:
  path: /travels/{travel}/steps/{step}/attachments
  methods: [GET]
  defaults:
    _controller: AppBundle:StepAttachment:list

app_step_attachment_new:
  path: /travels/{travel}/steps/{step}/attachments
  methods: [POST]
  defaults:
    _controller: AppBundle:StepAttachment:new