app_step_list:
  path: /travels/{travel}/steps
  methods: [GET]
  defaults:
    _controller: 'AppBundle:Step:list'

app_step_new:
  path: /travels/{travel}/steps
  methods: [POST]
  defaults:
    _controller: 'AppBundle:Step:new'

app_step_get:
  path: /travels/{travel}/steps/{step}
  methods: [GET]
  defaults:
    _controller: 'AppBundle:Step:get'

app_step_edit:
    path: /travels/{travel}/steps/{step}/edit
    defaults:
      _controller: 'AppBundle:Step:edit'

app_step_delete:
    path: /travels/{travel}/steps/{step}/delete
    defaults:
      _controller: 'AppBundle:Step:delete'