app_travel_list:
    path: /travels
    methods: [GET]
    defaults:
      _controller: 'AppBundle:Travel:list'

app_travel_new:
    path: /travels
    methods: [POST]
    defaults:
      _controller: 'AppBundle:Travel:new'

app_travel_view:
    path: /travels/{travel}
    methods: [GET]
    defaults:
      _controller: 'AppBundle:Travel:view'

app_travel_edit:
    path: /travels/{travel}
    methods: [PATCH]
    defaults:
      _controller: 'AppBundle:Travel:edit'

app_travel_delete:
    path: /travels/{travel}
    methods: [DELETE]
    defaults:
      _controller: 'AppBundle:Travel:delete'