app_travel:
  resource: routing/travel.yml

app_step:
  resource: routing/step.yml

app_upload:
  resource: routing/upload.yml

app_attachment_new:
    path: /travels/{travel}/attachments/new
    defaults:
      _controller: 'AppBundle:Attachment:new'

app_attachment_download:
    path: /travel/{travel}/attachments/{attachment}/download
    defaults:
      _controller: 'AppBundle:Attachment:download'

app_attachment_edit:
    path: /travel/{travel}/attachments/{attachment}/edit
    defaults:
      _controller: 'AppBundle:Attachment:edit'

app_attachment_delete:
    path: /travel/{travel}/attachments/{attachment}/delete
    defaults:
      _controller: 'AppBundle:Attachment:delete'

app_attachment_new_step:
    path: /travels/{travel}/steps/{step}/attachments/new
    defaults:
      _controller: 'AppBundle:Attachment:newForStep'