app_travel_list:
    path: /travels
    methods: [GET]
    defaults:
      _controller: 'AppBundle:Travel:list'

app_travel_new:
    path: /travels
    methods: [POST]
    defaults:
      _controller: 'AppBundle:Travel:new'

app_travel_view:
    path: /travels/{travel}
    defaults:
      _controller: 'AppBundle:Travel:view'

app_travel_edit:
    path: /travels/{travel}/edit
    defaults:
      _controller: 'AppBundle:Travel:edit'

app_travel_delete:
    path: /travels/{travel}/delete
    defaults:
      _controller: 'AppBundle:Travel:delete'

app_step_new:
    path: /travels/{travel}/steps/new
    defaults:
      _controller: 'AppBundle:Step:new'

app_step_edit:
    path: /travels/{travel}/steps/{step}/edit
    defaults:
      _controller: 'AppBundle:Step:edit'

app_step_delete:
    path: /travels/{travel}/steps/{step}/delete
    defaults:
      _controller: 'AppBundle:Step:delete'

app_attachment_new:
    path: /travels/{travel}/attachments/new
    defaults:
      _controller: 'AppBundle:Attachment:new'

app_attachment_download:
    path: /travel/{travel}/attachments/{attachment}/download
    defaults:
      _controller: 'AppBundle:Attachment:download'

app_attachment_edit:
    path: /travel/{travel}/attachments/{attachment}/edit
    defaults:
      _controller: 'AppBundle:Attachment:edit'

app_attachment_delete:
    path: /travel/{travel}/attachments/{attachment}/delete
    defaults:
      _controller: 'AppBundle:Attachment:delete'

app_attachment_new_step:
    path: /travels/{travel}/steps/{step}/attachments/new
    defaults:
      _controller: 'AppBundle:Attachment:newForStep'