services:
  app.normalizer.travel:
    class: AppBundle\Normalizer\TravelNormalizer

  app.normalizer.accomodation_step:
    class: AppBundle\Normalizer\Step\AccomodationStepNormalizer

  app.normalizer.tour_step:
    class: AppBundle\Normalizer\Step\TourStepNormalizer

  app.normalizer.transportation_step:
    class: AppBundle\Normalizer\Step\TransportationStepNormalizer

  app.normalizer.upload:
    class: AppBundle\Normalizer\UploadNormalizer
