services:
    app.fixture.example_factory.accomodation_step:
        class: AppBundle\Fixture\Factory\AccomodationStepExampleFactory
        arguments:
            - "@doctrine.orm.entity_manager"

    app.fixture.example_factory.tour_step:
        class: AppBundle\Fixture\Factory\TourStepExampleFactory
        arguments:
            - "@doctrine.orm.entity_manager"

    app.fixture.example_factory.transportation_step:
        class: AppBundle\Fixture\Factory\TransportationStepExampleFactory
        arguments:
            - "@doctrine.orm.entity_manager"

    app.fixture.example_factory.travel:
        class: AppBundle\Fixture\Factory\TravelExampleFactory
        arguments:
            - "@doctrine.orm.entity_manager"

    app.fixture.example_factory.user:
        class: AppBundle\Fixture\Factory\UserExampleFactory
        arguments:
            - "@doctrine.orm.entity_manager"
